project_name: terralens

before:
  hooks:
    - go mod download

builds:
  - main: .
    binary: terralens
    ldflags:
      - -X main.Version={{.Version}}
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

brews:
  - repository:
      owner: kishaningithub
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/kishaningithub/terralens
    description: See your Terraform state world with clarity and precision - TerraLens, your visual command center for infrastructure insight!
    license: MIT

nfpms:
  - id: terralens
    package_name: terralens
    homepage: https://github.com/kishaningithub/terralens
    description: See your Terraform state world with clarity and precision - TerraLens, your visual command center for infrastructure insight!
    maintainer: Kishan B <kishancs46@gmail.com>
    license: MIT
    formats:
      - apk
      - deb
      - rpm

kos:
  - main: .
    base_image: alpine
    repository: ghcr.io/kishaningithub/terralens
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - '{{.Version}}'
      - latest
    bare: true
    preserve_import_paths: false
