name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - name: Test
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

      - name: Check go releaser config
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: check
